# Generated by Django 6.0.1 on 2026-01-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código único (Barras/QR)', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=3, help_text='Peso exacto para camiones', max_digits=10)),
                ('es_fragil', models.BooleanField(default=False)),
                ('largo_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alto_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
